/**
 * Libellés des pages /a-louer, /projets et de leurs pages de projet.
 * Aucun contenu de projet ici — celui-là vient de la collection.
 */
export const projetsCopy = {
  fr: {
    liste: {
      eyebrow: 'À louer',
      title: 'Logements à louer',
      lead: 'Nos immeubles neufs actuellement en location et à venir.',
      empty: 'Aucun projet en location pour le moment.',
    },
    // Page /projets-a-venir. Les chantiers annoncés, qui ne se louent pas
    // encore : aucun libellé ici ne promet une visite, un prix ni une
    // disponibilité.
    aVenir: {
      title: 'Projets à venir',
      lead: "Les immeubles que MauDev construit en ce moment. Ils ne sont pas encore en location — voici ce qui est arrêté à ce jour.",
      empty: 'Aucun projet annoncé pour le moment.',
      visuelsSoon: 'Visuels à venir',
      chantier: 'Le chantier',
      chantierNote: 'Vue de drone du chantier en cours.',
      contactTitle: 'Vous voulez être prévenu ?',
      contactCta: 'Écrire à MauDev',
      toRent: 'Voir les logements à louer',
    },
    realises: {
      eyebrow: 'Réalisations',
      title: 'Projets réalisés',
      lead: "Les immeubles que MauDev a construits, rénovés ou livrés à ce jour.",
      empty: 'Aucun projet réalisé publié pour le moment.',
      counts: (projets: number, villes: number) =>
        `${projets} projets · ${villes} ${villes > 1 ? 'municipalités' : 'municipalité'}`,
      // Décompte d'un groupe de municipalité, sur /projets comme dans l'index
      // de l'accueil : les deux affichent le même nombre, donc le même texte.
      parVille: (n: number) => (n > 1 ? `${n} projets livrés` : `${n} projet livré`),
      toRent: 'Voir les projets à louer',
      voirTout: 'Voir toutes les réalisations',
    },
    detail: {
      back: 'Tous les projets à louer',
      // Une réalisation ne se loue plus : le retour mène à la grille des
      // réalisations, pas à celle des logements disponibles.
      backRealises: 'Toutes les réalisations',
      // « Les logements et tarifs » sur une réalisation annoncerait des prix
      // qui n'existent plus. Le contenu est le même — types et superficies —
      // le titre ne promet que ça.
      logementsRealise: 'Les logements',
      faits: 'En bref',
      realiseContactTitle: 'Un projet comme celui-ci ?',
      realiseContactLead:
        "Ce projet est livré et loué. Écrivez-nous pour parler d'un projet à venir, ou voyez ce qui se loue en ce moment.",
      unites: 'logements',
      etages: 'étages',
      livraison: 'Livraison',
      louees: 'déjà loués',
      inclusions: 'Ce qui est inclus',
      inclusionsPlus: 'Aussi disponible :',
      paying: 'en option',
      logements: 'Les logements et tarifs',
      type: 'Type',
      superficie: 'Superficie',
      prix: 'Loyer',
      inclus: 'Inclus',
      onRequest: 'Sur demande',
      perMonth: '/mois',
      unavailable: 'Complet',
      options: 'Options',
      photos: 'Photos',
      renders: 'Rendus 3D',
      plans: 'Plans',
      pauseVideo: 'Mettre la vidéo en pause',
      playVideo: 'Lire la vidéo',
      planUnits: 'Unités',
      planAlt: 'Plan {t}',
      viewPlans: 'Voir les plans',
      hidePlans: 'Masquer',
      planCount: '{n} plans',
      openPlan: 'Agrandir le plan',
      prevPlan: 'Plan précédent',
      nextPlan: 'Plan suivant',
      planLightboxCount: 'Plan {i} sur {n}',
      openPhoto: 'Agrandir la photo',
      closePhoto: 'Fermer',
      prevPhoto: 'Photo précédente',
      nextPhoto: 'Photo suivante',
      photoCount: 'Photo {i} sur {n}',
      emplacement: 'Emplacement',
      carteVoir: 'Afficher la carte',
      carteAvis: "La carte vient de Google. L'afficher charge des ressources de Google et dépose des témoins.",
      carteOuvrir: 'Ouvrir dans Google Maps',
      carteTitre: 'Carte de {a}',
      visitCta: 'Prendre rendez-vous pour une visite',
      // Sur une carte de logement : même destination, place de trois mots.
      visiter: 'Visiter ce logement',
      visitLead: "Venez voir les logements sur place, on s'organise selon vos disponibilités.",
      contactTitle: 'Intéressé par ce projet ?',
      contactLead: 'Écrivez-nous pour connaître les disponibilités.',
      contactCta: 'Écrire à MauDev',
      noMedia: 'Les photos et les plans de ce projet seront publiés dès leur réception.',
    },
  },
  en: {
    liste: {
      eyebrow: 'For rent',
      title: 'Apartments for rent',
      lead: 'Our new buildings currently leasing and coming soon.',
      empty: 'No project is leasing at the moment.',
    },
    aVenir: {
      title: 'Upcoming projects',
      lead: 'The buildings MauDev is putting up right now. They are not yet available to rent — here is what has been settled so far.',
      empty: 'No announced project at the moment.',
      visuelsSoon: 'Visuals coming',
      chantier: 'The site',
      chantierNote: 'Drone view of the site under construction.',
      contactTitle: 'Want to be notified?',
      contactCta: 'Email MauDev',
      toRent: 'See the apartments for rent',
    },
    realises: {
      eyebrow: 'Track record',
      title: 'Completed projects',
      lead: 'The buildings MauDev has built, renovated or delivered to date.',
      empty: 'No completed project published yet.',
      counts: (projets: number, villes: number) =>
        `${projets} projects · ${villes} ${villes > 1 ? 'municipalities' : 'municipality'}`,
      parVille: (n: number) => (n > 1 ? `${n} completed projects` : `${n} completed project`),
      toRent: 'See the projects for rent',
      voirTout: 'See all completed projects',
    },
    detail: {
      back: 'All projects for rent',
      backRealises: 'All completed projects',
      logementsRealise: 'The apartments',
      faits: 'At a glance',
      realiseContactTitle: 'Looking for something like this?',
      realiseContactLead:
        'This project is delivered and fully leased. Write to us about an upcoming project, or see what is leasing right now.',
      unites: 'apartments',
      etages: 'floors',
      livraison: 'Delivery',
      louees: 'already leased',
      inclusions: "What's included",
      inclusionsPlus: 'Also available:',
      paying: 'optional',
      logements: 'Apartments and rates',
      type: 'Type',
      superficie: 'Area',
      prix: 'Rent',
      inclus: 'Included',
      onRequest: 'On request',
      perMonth: '/month',
      unavailable: 'Fully leased',
      options: 'Options',
      photos: 'Photos',
      renders: '3D renderings',
      plans: 'Floor plans',
      pauseVideo: 'Pause video',
      playVideo: 'Play video',
      planUnits: 'Units',
      planAlt: 'Floor plan {t}',
      viewPlans: 'View plans',
      hidePlans: 'Hide',
      planCount: '{n} plans',
      openPlan: 'Enlarge floor plan',
      prevPlan: 'Previous plan',
      nextPlan: 'Next plan',
      planLightboxCount: 'Plan {i} of {n}',
      openPhoto: 'Enlarge photo',
      closePhoto: 'Close',
      prevPhoto: 'Previous photo',
      nextPhoto: 'Next photo',
      photoCount: 'Photo {i} of {n}',
      emplacement: 'Location',
      carteVoir: 'Show the map',
      carteAvis: 'The map comes from Google. Showing it loads Google resources and sets cookies.',
      carteOuvrir: 'Open in Google Maps',
      carteTitre: 'Map of {a}',
      visitCta: 'Book a viewing',
      visiter: 'Book a viewing',
      visitLead: 'Come see the apartments in person — we work around your schedule.',
      contactTitle: 'Interested in this project?',
      contactLead: 'Write to us to ask about availability.',
      contactCta: 'Email MauDev',
      noMedia: 'Photos and floor plans for this project will be published as soon as we receive them.',
    },
  },
} as const;
